language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38

install: pip install yapf

script:
  - make format
  - git update-index --refresh
  - git diff-index --ignore-submodules --quiet HEAD
  - git clone https://github.com/symbiflow/prjxray
  - cd prjxray 
  - git submodule update --init --recursive
  - sudo apt-get install virtualenv python3 python3-pip python3-virtualenv python3-yaml
  - make env
  - source settings/artix7.sh
  - cd ..
  - python run_tests.py samples/128b1/alt.fasm samples/128b1/init/init.mem samples/128b1/mapping.mdd samples/128b1/patched.fasm samples/128b1/real.fasm mem/ram
  #- python run_tests.py samples/8kb1/alt.fasm samples/8kb1/init/init.mem samples/8kb1/mapping.mdd samples/8kb1/patched.fasm samples/8kb1/real.fasm
  #- python run_tests.py samples/2kb72/alt.fasm samples/2kb72/init/init.mem samples/2kb72/mapping.mdd samples/2kb72/patched.fasm samples/2kb72/real.fasm

after_failure:
  - git diff

notifications:
  email: false
